version: "3.3"

services:
  app:
    build: ./lincride
    container_name: "lincride-backend"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./lincride:/usr/src/app
    ports:
      - "8000:8000"