# Generated by Django 3.2.9 on 2025-02-13 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_per_kilometer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, help_text='Base fare for vehicle', max_digits=100)),
                ('demand_level', models.CharField(choices=[('normal', 'Normal'), ('peak', 'Peak')], default='normal', max_length=10)),
                ('traffic_level', models.CharField(choices=[('normal', 'Normal'), ('peak', 'Peak')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('demand_level', 'traffic_level')},
            },
        ),
    ]
